# MIT License
#
# Copyright (c) 2022 Adrian F. Hoefflin [srccircumflex]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

########################################################################################################################
# LEGEND
# %         user-depend files (fstrings)
# --        recommendation
# \=        default
# +=        overwritten by user-associated-configuration in SefiTrash/etc/BOARD*  (HOST-SIDE)
#
########################################################################################################################
# $$$CONFIG_SCOPES
# 1 : Host
# 2 : Client
# CONFIG_SCOPES$$$
#
# $$$CONFIG_UNITS
# Miscellaneous
# Permissions
# Restrictions
# Verification
# Intervention  $[INTERVENT_PORT INTERVENT_IP]
# MailAlert     $[MAIL_CRYPT MAIL_XF MAIL_SMTP_ADDR MAIL_SMTP_PORT MAIL_CRYPT MAIL_SENDER_MAIL]
# Connection
# IO_Bypass     $[BYPASS_IP BYPASS_PORT BYPASS_CLI_IP BYPASS_CLI_PORT]
# Inspection    $[INSPECT_PORT INSPECT_IP]
# Logging
# Development
# CONFIG_UNITS$$$
#
# $$$CONFIG_TYPES
# str
# bool
# dir
# codec
# wfile
# rformfile
# fsc
# rfile
# list
# point
# int
# pars
# re
# collect
# choice
# intpair
# pass
# CONFIG_TYPES$$$
########################################################################################################################
# CONFIGURATION LEVELS
# _defaults_             # LV0
# <this file>            # LV2  --do not edit this file
# commandline            # LV3
RC_FILE_LV1: str = None  # LV4 overwritten if access to ″<home>/.sefitrarc.txt″@win32,″<home>/.sefitrarc″@linux         Miscellaneous$0$rfile;{6}$
USER: str = None         # LV5 for each access to ″SefiTrash/etc/<USER-as-prefix>.<any>″                                Miscellaneous$0$str
########################################################################################################################
DEFAULT_USER: str = None             # \=root                                                                           Miscellaneous$0$str
########################################################################################################################
# HOST CONFIGS
# paring
PARING_LIFETIME: int = None         # \=30s                                                                             Restrictions$1$int;{^[0-9]+$}$
SENSITIVE_PARING: bool = None       # del providing, if verification fails  \=False                                     Restrictions$1$bool
# etc
BOARD_PATH_RULE: str = None         # \=<_file_conf.py                                                                  Permissions$1$rfile;{6}$
BOARD_CALL_RULE: str = None         # \=<_file_conf.py                                                                  Permissions$1$rfile;{6}$
BOARD_CLIENT_RULE: str = None       # \=<_file_conf.py                                                                  Permissions$1$rfile;{6}$
BOARD_USERS: str = None             # \=<_file_conf.py                                                                  Permissions$1$rfile;{6}$
# login-files
FSC_HOST_SPICE_FILE: str = None     # % \=<_file_conf.py                                                                Verification$1$rformfile;{6}$
FSC_HOST_XF: str = None             # % \=<_file_conf.py                                                                Verification$1$rformfile;{6}$
FSC_HOST_TABLE_FILE: str = None     # % \=<_file_conf.py                                                                Verification$1$rformfile;{6}$
FSC_PEPPER_HOST: str = None         # % \=<_file_conf.py                                                                Verification$1$rformfile;{6}$
FSC_XF_LIFETIME: int = None         # \=2764800s                                                                        Verification$1$int;{^[0-9]+$}$
# auth- firewall- config
FIREWALL_RESET_INTERVAL: int = None  # \=86400                                                                          Restrictions$1$int;{^[0-9]+$}$
LAPSLOGIN_LIM_RUNTIME: int = None    # \=3 +=_users                                                                     Restrictions$1$int;{^[0-9]+$}$
LAPSLOGIN_DEL: bool = None           # \=1 +=_users                                                                     Restrictions$1$bool
MAX_CLIENT_CACHE: int = None         # \=50                                                                             Restrictions$1$int;{^[0-9]+$}$
# intervention
INTERVENT_IP: str = None            # \=127.2.4.8                                                                       Intervention$1$re;{^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$}$
INTERVENT_PORT: int = None          # \=1632                                                                            Intervention$1$int;{^[0-9]+$}$
PRINT_INTERVENTION_ONOFF: tuple[str,str] = None         # 'ansi' | 'utf' | 'ordin' | <_rc._def_print> tuple{2}  \='ordin'        Intervention$1$choice;{ansi;utf;ordin}$
PRINT_INTERVENTION_FLUSH: tuple[str,] = None            # 'ansi' | 'utf' | 'ordin' | <_rc._def_print> tuple{...}  \='ordin'      Intervention$1$choice;{ansi;utf;ordin}$
PRINT_INTERVENTION_ERROR: str = None                    # 'ansi' | 'utf' | 'ordin' | <_rc._def_print> str  \='ordin'             Intervention$1$choice;{ansi;utf;ordin}$
# development
KILL_TIMEOUT: float = None          # \=2.0s                                                                            Development$1$point;{^[0-9]*\.[0-9]+$}$
LISTEN_TIMEOUT: float = None        # \=2.0s                                                                            Development$1$point;{^[0-9]*\.[0-9]+$}$
# miscellaneous
SHUTDOWN_EXCO: tuple[int,] = None   # \=(0, 1)                                                                          Miscellaneous$1$collect;{tuple:::;u:Normal exit:i:0;u:Unhandled error:i:1;l:SIGTERM:i:-15;l:SIGKILL:i:-9;w:SIGINT:i:2;w:SIGBREAK:i:21;w:SIGTERM:i:15}$
# mail-alert
MAIL_XF: str = None                 # % \=<_file_conf.py                                                                MailAlert$1$rformfile;{6}$
MAIL_FSC: tuple[int,tuple[int,int],int] = None  # (IV, (part, prio) hops) | '[1-9]\d{0,2}[+-][1-9]\.[1-9]'  \=None      MailAlert$1$fsc
MAIL_XFSEED: str = None             # hash sha256  \=None                                                               MailAlert$1$pass;{sha256}$
MAIL_SMTP_ADDR: str = None          # \=False                                                                           MailAlert$1$str
MAIL_SMTP_PORT: int = None          # \=False                                                                           MailAlert$1$int;{^[0-9]+$}$
MAIL_CRYPT: str = None    # ('SSL' | 'TLS'):self-signed-; lowercase:unverified- -ssl-context \=None                     MailAlert$1$choice;{SSL;TLS;ssl;tls}$
MAIL_USER: str = None               # \=None                                                                            MailAlert$1$str
MAIL_SENDER_MAIL: str = None        # \=False                                                                           MailAlert$1$str
MAIL_RECEIVER_MAIL: str = None      # \=None                                                                            MailAlert$1$str
MAIL_BCC: str = None                # \=None                                                                            MailAlert$1$str
# mail-alert config
MAILALERTLV_BLACKBOX: int = None    # \=61                                                                              MailAlert$1$int;{^[0-9]+$}$
MAILALERTLV_FIREWALL: int = None    # \=55                                                                              MailAlert$1$int;{^[0-9]+$}$
MOD_LOGIN_TO_ALERT: bool = None     # \=False                                                                           MailAlert$1$bool

########################################################################################################################
# CLIENT CONFIGS
# invalid port              : 0
# well-known/system ports   : - 1023
# IANA registered ports     : 1024 - 49151
# dynamic/private/ephemeral : 49152 – 65535
PORT_RANGE_ESTABLISH: tuple[int,int] = None              # \=(50020, 50030)                                             Connection$2$intpair;{fist:^[0-9]+$;last:^[0-9]+$}$

IP_RECEIVER: list[str,] = None    # string or list (range supported″192.168.1-5.2-7″)  \=127.0.0.1                      Connection$2$list;{([0-9]{1,3}|[0-9]{1,3}-[0-9]{1,3})\.([0-9]{1,3}|[0-9]{1,3}-[0-9]{1,3})\.([0-9]{1,3}|[0-9]{1,3}-[0-9]{1,3})\.([0-9]{1,3}|[0-9]{1,3}-[0-9]{1,3})}$
# response timeouts
PING_TIMEOUT: float = None    # * 20        # \=0.5s                                                                    Connection$2$point;{^[0-9]*\.[0-9]+$}$
RESPONSE_TIMEOUT: int = None  # * ↓         # \=50                                                                      Connection$2$int;{^[0-9]+$}$
RESPONSE_TIMEOUT_ADJUST: float = None       # \=0.2s                                                                    Connection$2$point;{^[0-9]*\.[0-9]+$}$
# auth config
FSC_ESTABLISH_PEPPER: str = None            # % \=<_file_conf.py                                                        Verification$2$rformfile;{6}$
FSC_ESTABLISH_TABLE_FILE: str = None        # % \=<_file_conf.py                                                        Verification$2$rformfile;{6}$
TIMESTAMP_LIFETIME: int = None              # \=90s                                                                     Verification$2$int;{^[0-9]+$}$
# IO bypassing
BYPASS_IP: str = None                       # \=None                                                                    IO_Bypass$2$re;{^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$}$
BYPASS_PORT: int = None                     # \=None                                                                    IO_Bypass$2$int;{^[0-9]+$}$
BYPASS_CLI_IP: str = None                   # \=None                                                                    IO_Bypass$2$re;{^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$}$
BYPASS_CLI_PORT: int = None                 # \=None                                                                    IO_Bypass$2$int;{^[0-9]+$}$
MOD_SET_BYPASS: bool = None                 # \=False                                                                   IO_Bypass$2$bool

########################################################################################################################
# UNI CONFIGS
# invalid port              : 0
# well-known/system ports   : - 1023
# IANA registered ports     : 1024 - 49151
# dynamic/private/ephemeral : 49152 – 65535
IP_LOCAL: str = None       # '<ip>' | 'get local' | 'get local from <[dns]ip>' | 'get public'  \=127.0.0.1              Connection$0$pars;{^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^get local$|^get public$|^get local from [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$}$
PORT_RANGE_RECEIVER: tuple[int,int] = None       # \=(50000, 50000)                                                     Connection$0$intpair;{fist:^[0-9]+$;last:^[0-9]+$}$
# defaults
BASIC_FSC_PEPPER: tuple[int,tuple[int,int],int] = None       # (IV, (part, prio) hops) | '[1-9]\d{0,2}[+-][1-9]\.[1-9]'  \=(61, (0, 1), 3)    Verification$0$fsc
# log-sock-stream
INSPECT_IP: str = None              # \=127.1.1.2                                                                       Inspection$0$re;{^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$}$
INSPECT_PORT: int = None            # \=35813                                                                           Inspection$0$int;{^[0-9]+$}$
# bridge src/dst
SRC_BASIC_ROOT: str = None          # \=pwd                                                                             Miscellaneous$0$dir;{2}$
DST_BASIC_ROOT: str = None          # \=pwd                                                                             Miscellaneous$0$dir;{2}$
#           COUNTERMEASURE          ####################################################################################
# different sources
MAX_BAD_CLIENTS_LV1: int = None         # \=20                                                                          Restrictions$0$int;{^[0-9]+$}$
MAX_BAD_CLIENTS_LV2: int = None         # \=50                                                                          Restrictions$0$int;{^[0-9]+$}$
MAX_BAD_CLIENTS_LV3: int = None         # \=70                                                                          Restrictions$0$int;{^[0-9]+$}$
MAX_BAD_CLIENTS_EXEC_LV1: str = None    # 'sleep1' | 'sleep2' | 'sleep3' | 'shutdown' | <_rc.exec_strings> '<exec-str>'  \='sleep2'   Restrictions$0$choice;{sleep1;sleep2;sleep3;shutdown}$
MAX_BAD_CLIENTS_EXEC_LV2: str = None    # 'sleep1' | 'sleep2' | 'sleep3' | 'shutdown' | <_rc.exec_strings> '<exec-str>'  \='sleep3'   Restrictions$0$choice;{sleep1;sleep2;sleep3;shutdown}$
MAX_BAD_CLIENTS_EXEC_LV3: str = None    # 'sleep1' | 'sleep2' | 'sleep3' | 'shutdown' | <_rc.exec_strings> '<exec-str>'  \='sutdown'  Restrictions$0$choice;{sleep1;sleep2;sleep3;shutdown}$
# equal source
MAX_BAD_CLIENT_HIT_LV1: int = None      # \=12                                                                          Restrictions$0$int;{^[0-9]+$}$
MAX_BAD_CLIENT_HIT_LV2: int = None      # \=30                                                                          Restrictions$0$int;{^[0-9]+$}$
MAX_BAD_CLIENT_HIT_LV3: int = None      # \=60                                                                          Restrictions$0$int;{^[0-9]+$}$
MAX_BAD_CLIENT_HIT_EXEC_LV1: str = None  # 'sleep1' | 'sleep2' | 'sleep3' | 'shutdown' | <_rc.exec_strings> '<exec-str>'  \='sleep1'    Restrictions$0$choice;{sleep1;sleep2;sleep3;shutdown}$
MAX_BAD_CLIENT_HIT_EXEC_LV2: str = None  # 'sleep1' | 'sleep2' | 'sleep3' | 'shutdown' | <_rc.exec_strings> '<exec-str>'  \='sleep2'    Restrictions$0$choice;{sleep1;sleep2;sleep3;shutdown}$
MAX_BAD_CLIENT_HIT_EXEC_LV3: str = None  # 'sleep1' | 'sleep2' | 'sleep3' | 'shutdown' | <_rc.exec_strings> '<exec-str>'  \='shutdown'  Restrictions$0$choice;{sleep1;sleep2;sleep3;shutdown}$
# verification
#  verification requires minimum two unverified connects; ping and enrolment
#  counts the following login in case it fails
MAX_UNVERIFIED_LV1: int = None          # \=5                                                                           Restrictions$0$int;{^[0-9]+$}$
MAX_UNVERIFIED_LV2: int = None          # \=5                                                                           Restrictions$0$int;{^[0-9]+$}$
MAX_UNVERIFIED_LV3: int = None          # \=8                                                                           Restrictions$0$int;{^[0-9]+$}$
MAX_UNVERIFIED_EXEC_LV1: str = None  # 'ban' | 'sleep1' | 'sleep2' | 'sleep3' | 'shutdown' | <_rc.exec_strings> '<exec-str>'  \='ban'       Restrictions$0$choice;{ban;sleep1;sleep2;sleep3;shutdown}$
MAX_UNVERIFIED_EXEC_LV2: str = None  # 'ban' | 'sleep1' | 'sleep2' | 'sleep3' | 'shutdown' | <_rc.exec_strings> '<exec-str>'  \='ban'       Restrictions$0$choice;{ban;sleep1;sleep2;sleep3;shutdown}$
MAX_UNVERIFIED_EXEC_LV3: str = None  # 'ban' | 'sleep1' | 'sleep2' | 'sleep3' | 'shutdown' | <_rc.exec_strings> '<exec-str>'  \='shutdown'  Restrictions$0$choice;{ban;sleep1;sleep2;sleep3;shutdown}$
#           LOGGING                 ####################################################################################
# files
LOG_FIREWALL: str = None        # devnull if None  \=<_file_conf.py                                                     Logging$0$wfile;{6}$
LOG_CALL: str = None            # devnull if None  \=<_file_conf.py                                                     Logging$0$wfile;{6}$
LOG_PATH: str = None            # devnull if None  \=<_file_conf.py                                                     Logging$0$wfile;{6}$
LOG_BRIDGE: str = None          # devnull if None  \=<_file_conf.py                                                     Logging$0$wfile;{6}$
LOG_KILL: str = None            # devnull if None  \=<_file_conf.py                                                     Logging$0$wfile;{6}$
LOG_SOCKIO: str = None          # devnull if None  \=<_file_conf.py                                                     Logging$0$wfile;{6}$
LOG_BLACKBOX: str = None        # devnull if None  \=<_file_conf.py                                                     Logging$0$wfile;{6}$
LOG_LOGSTREAMERR: str = None    # devnull if None  \=<_file_conf.py                                                     Logging$0$wfile;{6}$
# log files backup config
LOGMAX_LOGSIZE: int = None      # \=10*1024*1024                                                                        Logging$0$int;{^[0-9]+$}$
LOGMAX_BACKUPS: int = None      # \=3                                                                                   Logging$0$int;{^[0-9]+$}$
# other log-files
LOG_REMOTE: str = None          # \=<_file_conf.py                                                                      Logging$0$wfile;{6}$
LOG_BASIC_FILE: str = None      # devnull if None  \=None                                                               Logging$0$wfile;{6}$
# levels
#        61: 'ALERT'
#        60: 'FATAL',
#        55: 'COUNTER',
#        54: 'PREVENT',
#        50: 'CRITICAL',
#        45: 'DEPTHERR',
#        40: 'ERROR',
#        35: 'HARD',
#        30: 'WARNING',
#        25: 'INIT',
#        20: 'INFO',
#        15: 'DATA-I',
#        10: 'DEBUG',
#        5: 'DATA-O',
#        0: 'NULL'
LOGLV_FIREWALL: list[int,int] = None        # [<stream>, <write>]  \=[20,30]                                            Logging$0$intpair;{stream:^[0-9]+$;write:^[0-9]+$}$
LOGLV_CALL: list[int,int] = None            # [<stream>, <write>]  \=[30,30]                                            Logging$0$intpair;{stream:^[0-9]+$;write:^[0-9]+$}$
LOGLV_PATH: list[int,int] = None            # [<stream>, <write>]  \=[30,30]                                            Logging$0$intpair;{stream:^[0-9]+$;write:^[0-9]+$}$
LOGLV_BRIDGE: list[int,int] = None          # [<stream>, <write>]  \=[20,30]                                            Logging$0$intpair;{stream:^[0-9]+$;write:^[0-9]+$}$
LOGLV_KILL: list[int,int] = None            # [<stream>, <write>]  \=[30,10]                                            Logging$0$intpair;{stream:^[0-9]+$;write:^[0-9]+$}$
LOGLV_SOCKIO: list[int,int] = None          # [<stream>, <write>]  \=[30,30]                                            Logging$0$intpair;{stream:^[0-9]+$;write:^[0-9]+$}$
LOGLV_BLACKBOX: list[int,int] = None        # [<stream>, <write>]  \=[1,60]                                             Logging$0$intpair;{stream:^[0-9]+$;write:^[0-9]+$}$
# mods
MOD_LOGLVTO_DEBUG: bool = None          # \=False                                                                       Logging$0$bool
MOD_LOGLVTO_BLACKBOX: bool = None       # \=False                                                                       Logging$0$bool
MOD_LOGLVTO_ALLS: int = None            # \=False                                                                       Logging$0$int;{^[0-9]+$}$
MOD_LOGLVTO_ALLF: int = None            # \=False                                                                       Logging$0$int;{^[0-9]+$}$
MOD_BGSTREAM: bool = None               # \=False@win32,True@linux                                                      Inspection$0$bool
MOD_STREAM_READLOOP: bool = None        # \=False                                                                       Inspection$0$bool
# other mods config
MAXSIZE_TOXICS: int = None      # 0=disabled | n  \=0                                                                   Logging$0$int;{^[0-9]+$}$
LOGPATH_TOXIC_DATA: str = None  # \=<_file_conf.py                                                                      Logging$0$dir;{2}$
#           PRINTING                ####################################################################################
PRINT_TIMEOUT_BAR: tuple[str,] = None                   # 'ansi' | 'utf' | 'ordin' | <_rc._def_print> tuple{20}  \='ordin'       Logging$2$choice;{ansi;utf;ordin}$
PRINT_STREAM_ARGS: tuple[dict,object,dict,dict] = None  # 'ansi' | 'utf' | 'ordin' | <_rc._def_print> tuple(kwargs[formater], class[msg-ansis], dict[lv-to-ansi-prefix], dict[lv-to-ansi-name])  \='ordin'     Logging$0$choice;{ansi;utf;ordin}$
PRINT_ICOS: object = None                               # 'ansi' | 'utf' | 'ordin' | <_rc._def_print> class[icos]  \='ordin'     Logging$0$choice;{ansi;utf;ordin}$
#           MISCELLANEOUS           ####################################################################################
# stats
#        # 0: 'st_mode',   # Permissions bits
#        # 1: 'st_ino',    # (Inode@UNIX, FileIndex@WINDOWS)
#        # 2: 'st_dev',    # Device identifier
#        # 3: 'st_nlink',  # Number of hard links
#        # 4: 'st_uid',    # User id
#        # 5: 'st_gid',    # Group id
#        6: 'st_size',   # Length
#        7: 'st_atime',  # Access time
#        8: 'st_mtime',  # Modification time
#        9: 'st_ctime'   # (MetadataChangeTime@UNIX, CreationTime@WINDOWS)
DIR_STAT_TAGS: dict = None                      # \=dict[6:* , 7:* , 8:* , 9:* ]                                        Miscellaneous$1$collect;{idict:::;u:Permissions bits:s:st_mode;l:Inode:s:st_ino;w:File index:s:st_dev;u:Device identifier:s:st_dev;u:Number of hard links:s:st_nlink;u:User id:s:st_uid;u:Group id:s:st_gid;u:Length:s:st_size;u:Access time:s:st_atime;u:Modification time:s:st_mtime;l:Metadata change time:s:st_ctime;w:Creation time:s:st_ctime}$
# https://docs.python.org/3.9/library/time.html#time.strftime
DIR_TIME_FORM: str = None                       # \="%y.%m.%d-%H:%M"                                                    Miscellaneous$2$str
# ssl
SSL_CERT_FILE: str = None           # \=<_file_conf.py                                                                  Verification$0$rfile;{6}$
SSL_KEY_FILE: str = None            # \=<_file_conf.py                                                                  Verification$0$rfile;{6}$
SSL_PASSWORD: str = None            # \=None                                                                            Verification$0$pass;{sha256}$
# developement
DAT_MAX_STACKS: int = None          # \=3                                                                               Development$0$int;{^[0-9]+$}$
DAT_MAXSIZE_HEADER: int = None   # * 64     # \=10                                                                      Development$0$int;{^[0-9]+$}$
DAT_SOCK_BUFFER: int = None                 # \=1024                                                                    Development$0$int;{^[0-9]+$}$
DAT_READ_BUFFER: int = None                 # \=1024*1024                                                               Development$0$int;{^[0-9]+$}$
LOC_ENC: str = None                         # \=utf8                                                                    Development$0$codec
SRM_ENC: str = None                         # \=utf8                                                                    Development$0$codec
LOG_ENC: str = None                         # \=utf8                                                                    Development$0$codec
QUEUE_TIMEOUT: float = None                 # \=0.5s                                                                    Development$0$point;{^[0-9]*\.[0-9]+$}$
CONRESET_TIMEOUT: float = None              # \=0.5s                                                                    Development$0$point;{^[0-9]*\.[0-9]+$}$

# EOF
########################################################################################################################
MAIN_ROOT: str = None                                                                                            # $eof$
########################################################################################################################
EOF: None = None
########################################################################################################################

#  --temporary define by command-line
PROVIDED_PARING_IP: str = None      # 1/2 part of paring; can be wildcard-ed (0)  HOST-SIDE
PROVIDED_PARING_USER: str = None    # 2/2 part of paring                          HOST-SIDE
DO_PAR: bool = None                 # CLIENT-SIDE

# EOF
########################################################################################################################

# INTERN / RUNTIME DEF
HOST_SIDE: bool = None
CLIENT_SIDE: bool = None
LATERAL_: bool = None
SIDE_: dict = None
CONFIGURE_: bool = None
SIG_SEQ: list = None
PROVIDED_PARING: list = None
AUTH_CONF: dict = None
INTERVENT_BINDING: tuple = None
INSPECT_BINDING: tuple = None
_SSL_CONT_RECEIVER: object = None
_SSL_CONT_SENDER: object = None
STREAM_FORMAT: dict = None
LEVEL_TO_ANSI_PREFIX: dict = None
LEVEL_TO_ANSI_NAME: dict = None
MSG_ANSI: object = None
SYS_ROOT: str = None
HOME_PATH: str = None
SYS_PLATFORM: str = None
_MAIL_SSL: object = None
_CNF_PROX: object = None
_BYPASS: object = None
_BYPASSED: object = None
PCONT: str = '\n'

# EOF
########################################################################################################################
# INTERN / KONST
from _rc._msg_strings import *
from functools import lru_cache
from re import compile
FROM_SUBCLASS = ('sleep1','sleep2','sleep3','shutdown','ban','ansi','utf','ordin')
IFDEFENDIF = {
    'BOARD_PATH_RULE': (b'#f! BOARD_PATH_RULE', b'#EOF! BOARD_PATH_RULE', b'#'),
    'BOARD_CALL_RULE': (b'#f! BOARD_CALL_RULE', b'#EOF! BOARD_CALL_RULE', b'#'),
    'BOARD_CLIENT_RULE': (b'#f! BOARD_CLIENT_RULE', b'#EOF! BOARD_CLIENT_RULE', b'#'),
    'BOARD_USERS': (b'#f! BOARD_USERS', b'#EOF! BOARD_USERS', b'#'),
}
lU_RC = '/.sefitrarc'
wU_RC = '/.sefitrarc.txt'
@lru_cache(10)
def BUFFER_ITER(length:int, _buffer=None):
    return range(length // (_buffer := DAT_SOCK_BUFFER if _buffer is None else _buffer) + bool(length % _buffer))
def EXP_EXIT(code=0):
    if SYS_PLATFORM == "w": input(f"[{code}]-")
    exit(code)
